// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"context"
)

type Querier interface {
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteRecipe(ctx context.Context, id int64) error
	GetAllRecipe(ctx context.Context) (Recipe, error)
	GetRecipe(ctx context.Context, id int64) (Recipe, error)
	ListRecipe(ctx context.Context, arg ListRecipeParams) ([]Recipe, error)
}

var _ Querier = (*Queries)(nil)
