apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-api-deployment
  labels:
    app: recipe-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-api
  template:
    metadata:
      labels:
        app: recipe-api
    spec:
      containers:
      - name: recipe-api
        image: 588247822263.dkr.ecr.ap-northeast-1.amazonaws.com/recipe:26d11447677c9fbbcd2a2750a0d91ada14b0926c
        ports:
        - containerPort: 8080