// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"time"
)

type Recipe struct {
	ID      int64  `json:"id"`
	Cuisine string `json:"cuisine"`
	// must be positive
	NumPeople           int64     `json:"num_people"`
	RecipeTime          string    `json:"recipe_time"`
	UnwantedIngredients string    `json:"unwanted_ingredients"`
	WantedIngredients   string    `json:"wanted_ingredients"`
	Recipe              string    `json:"recipe"`
	CreatedAt           time.Time `json:"created_at"`
}
